# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6c286adfbab8699b3207242ebfb1cf449be7f4b4fca1da071ef918f297c1f0b21b9e243b02b2bb6a90d599e73c39461458ef72e0c7406321d8c137f8f37486dc

test:
  secret_key_base: e9bd7b162fa47fa9e47eb386664a315c5919260c19562685d5a2645b5566a3f5ed6992e4410fa417d0ef139c4d8618b6ca88498a0ceae8cf75ecdc60898ddd85

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
